### PR TITLE
Bump selectize from 0.12.4 to 0.12.6

### PR DESCRIPTION
**Pull request by davidbgk**
Incidentally fix the bug when 2 keywords are typed and the first one doesn’t anymore appear in the list of items.

### CODE REVIEW

**Comment by davidbgk** [comment]
I guess it has been resolved by https://github.com/selectize/selectize.js/commit/e9da17589e38f98a8aea720f827e03f4233a39cd

But it's hard to find given the [changelog](https://github.com/selectize/selectize.js/blob/master/CHANGELOG.md) is not anymore maintained, I had to [guess from the diff](https://github.com/selectize/selectize.js/compare/v0.12.4...v0.12.6).

Time for a stimulus version? 🤔

**Comment by ronnix** [comment]
Bug fixes FTW!

**Comment by ronnix** [comment]
WTF

**Comment by davidbgk** [comment]
autorebase FTL 😛

**Comment by ronnix** [comment]
Manual rebase FTW !

**Pull request merged**
