### PR TITLE
Fix Texte.get_or_create_from_ref() with DBSession

### PR DESCRIPTION
**Pull request by davidbgk**
When we import get_one_or_create within the method to avoid circular imports it looks to mess up with DB session in some circonstances (huey tasks).

Switching to a manual get or create.

### CODE REVIEW

**Comment by davidbgk** [comment]
It doesn't resolve the issue on zam-demo 😢

**Comment by ronnix** [comment]
Close ?

**Comment by ronnix** [comment]
Ok I'll rebase it on top of #651 (otherwise they'll conflict)

**Comment by ronnix** [comment]
I'll rewrite the commit message too

**Comment by ronnix** [comment]
Not sure the bot did the right thing here... 🤖

**Comment by ronnix** [comment]
Or maybe GitHub is just confused

**Comment by ronnix** [comment]
If it's ok for you, I'll manually merge this into #651

**Comment by ronnix** [comment]
Ok I redid the rebase manually and now it looks better

**Pull request merged**
