### PR TITLE
Add fixtures closer to reality based on real data

### PR DESCRIPTION
**Pull request by davidbgk**

### CODE REVIEW

**Comment by ronnix** [comment]
I think I'll just squash the commits, to keep only what's related to fixtures in the history.

**Comment by davidbgk** [comment]
My intent was to use the Squash and merge button from Github, not enough?

**Comment by ronnix** [comment]
Ah ok, did not think of that. I guess I’m used to the developer doing the squashing, not GitHub?

-- 
Ronan Amicel

**Comment by davidbgk** [comment]
I didn't noticed you already did it, nevermind :)

**Comment by ronnix** [comment]
Not sure GitHub can do the squash when there are merge commits in the branch, by the way.

**Pull request merged**
