### PR TITLE
Events and journals

### PR DESCRIPTION
**Pull request by davidbgk**

### CODE REVIEW

**Comment by davidbgk** [comment]
At some point we will want to remove 2 migrations but let's do that while pairing to update the revision number together :)

**Comment by ronnix** [comment]
Trying to add the auto rebase label again (not sure why the bot removed it)

**Comment by ronnix** [comment]
(My hope is that this way we don’t need to merge master into the branch, or rebase it manually)

**Comment by davidbgk** [comment]
@ronnix there was a conflict so I think it's running fine :)

**Comment by ronnix** [comment]
Ah so maybe it removes the label when some human intervention is needed? 🤔

**Comment by davidbgk** [comment]
That would be (maybe too) clever!

**Comment by ronnix** [comment]
Merci, petit robot !

**Pull request merged**
