### PR TITLE
Handle not found resources as 404

### PR DESCRIPTION
**Pull request by davidbgk**

### CODE REVIEW

**Comment by ronnix** [comment]
Mmm... On a ça qui aurait dû faire le taf, du moins c’était l’intention : 
https://github.com/betagouv/zam/blob/99e5e03973aef036a5d772af14af3a0b2669c2e5/repondeur/zam_repondeur/views/errors.py

**Comment by davidbgk** [comment]
Ah, pas vu, peut-être pas importé ?

**Comment by ronnix** [comment]
Normalement le config.scan() explore tout le projet, sans que tu aies besoin d’importer toutes tes vues explicitement. C’est bizarre.

**Comment by ronnix** [comment]
https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/views.html#custom-exception-views

**Comment by ronnix** [comment]
I think I understand what's happening.

The `ResourceNotFound` exception is actually caught by the exception view tween, and we do return a 404. But the exception also goes through the rollbar tween before being handled, so we get a report. :-(

Subclassing from `HTTPNotFound` is thus a good idea. It will silence rollbar, as it ignores all instances of `WSGIHTTPException`.

**Pull request merged**
