### PR TITLE
Show deployed version (branch, sha1 & date) in HTML comment

### PR DESCRIPTION
**Pull request by ronnix**

### CODE REVIEW

**Comment by davidbgk** [comment]
If that's only for us, why not put it as a HTML comment?

**Comment by ronnix** [comment]
That was my initial idea, but then sometimes it's a pain to access the page source (e.g. on a tablet) so I thought I would make it easier to access. What do you think?

**Comment by davidbgk** [comment]
Or maybe a dedicated page? I dislike when a developer info adds some bloat to the user

**Comment by ronnix** [comment]
Ok, I'll make it hidden then!

**Pull request merged**
