### PR TITLE
Bump tinymce from 4.7.13 to 5.1.1 

### PR DESCRIPTION
**Pull request by davidbgk**
From 4.7.13 (2018-05-16) to 5.1.1 (2019-10-28) + including plugins, skins, themes and langs.

### CODE REVIEW

**Comment by ronnix** [comment]
https://www.tiny.cloud/docs-4x/changelog/

**Comment by davidbgk** [comment]
Not the first time I'm super confused with their website… I use the custom build generator: https://www.tiny.cloud/get-tiny/custom-builds/

I'll try to update directly to the 5.1 https://www.tiny.cloud/get-tiny/self-hosted/

**Comment by ronnix** [comment]
Looks like the toolbar is less compact. Should we remove the cut/copy/paste buttons?
image

**Comment by davidbgk** [comment]
It does fit in my screen, maybe we can check with @MelodieDahi to make sure the order in that bar is from the more relevant to the less?

Or we can remove features and wait for the crowd ;)

**Comment by MelodieDahi** [comment]
Fits in my screen too when I am at the office but we can think about removing features / reordering them indeed because I see some features on the bar that should be closer indeed (+ maybe Maitane saw something while watching users?)

**Pull request merged**
