### PR TITLE
CI: add periodic job to fetch amendements

### PR DESCRIPTION
**Pull request by ronnix**

### CODE REVIEW

**Comment by ronnix** [comment]
`Progress:  100.00% (6389/5285)` :thinking:

**Comment by davidbgk** [comment]
> `Progress: 100.00% (6389/5285)` 🤔

`bar.update(step=len(dossier_ref.lectures))` is plain wrong, it should be `bar.update(step=i)` where `i` is from enumerate 🤷‍♂

**Comment by davidbgk** [comment]
> > `Progress: 100.00% (6389/5285)` 🤔
> 
> `bar.update(step=len(dossier_ref.lectures))` is plain wrong, it should be `bar.update(step=i)` where `i` is from enumerate 🤷‍♂

Hopefully 0cb343549c109bd72218f36a8ede9b4291b48cd0 is fixing that.

**Comment by davidbgk** [comment]
I propose to close that PR, it consumes a bit of energy everyday for no value. We might want to extract some improvements in the fetch script?

**Pull request closed without merging**
